import ReactQueryProvider from '@/components/providers/ReactQueryProvider'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Toaster } from '@/components/ui/toaster'
import { ReduxProviders } from '@/redux/Providers'
import { ModalProvider } from '@/providers/modal-providers'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" dir="rtl">
      <body className={inter.className}>
        <ReduxProviders>
          <ReactQueryProvider>
            <ModalProvider />
            <Toaster />
            {children}
          </ReactQueryProvider>
        </ReduxProviders>
      </body>
    </html>
  )
}
