import ReactQueryProvider from '@/components/providers/ReactQueryProvider'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Toaster } from '@/components/ui/toaster'
import { ReduxProviders } from '@/redux/Providers'
import { ModalProvider } from '@/providers/modal-providers'
import localFont from 'next/font/local'

const inter = Inter({ subsets: ['latin'] })
const primaryFont = localFont({
  src: '../public/fonts/FarsiFont.woff2',
  variable: '--font-sans',
})
const numericFont = localFont({
  src: '../public/fonts/FarsiAdad.woff2',
  variable: '--font-adad',
})
const numericBoldFont = localFont({
  src: '../public/fonts/FarsiAdad-Bold.woff2',
  variable: '--font-adad-bold',
})
const numericRegularFont = localFont({
  src: '../public/fonts/FarsiAdad-Regular.woff2',
  variable: '--font-adad-reg',
})
export const metadata: Metadata = {
  title: 'فروشگاه',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" dir="rtl">
      <body className={`${primaryFont.variable} font-farsi adad  antialiased`}>
        <ReduxProviders>
          <ReactQueryProvider>
            <ModalProvider />
            <Toaster />
            {children}
          </ReactQueryProvider>
        </ReduxProviders>
      </body>
    </html>
  )
}
